require("tmg.set")
require("tmg.remap")
require("tmg.lspconfig")
require("tmg.cmp")
require("tmg.null-ls")
require("tmg.gitsigns")
require("tmg.lualine")
-- require("tmg.lspsaga")
require("tmg.indent-blankline")
require("tmg.bufferline")
require("tmg.autopairs")
require("tmg.telescope")
require("tmg.ufo")
