require("tmg.set")
require("tmg.remap")
require("mason").setup()
require("mason-lspconfig").setup()
require("tmg.lspconfig")
require("tmg.cmp")
require("tmg.null-ls")
require("tmg.gitsigns")
require("tmg.lualine")
-- require("tmg.lspsaga")
require("tmg.indent-blankline")
require("tmg.bufferline")
require("tmg.autopairs")
require("tmg.telescope")

require("luasnip.loaders.from_vscode").lazy_load()
